### ISSUE TITLE
Production build failure

### ISSUE THREAD

**Issue by ghost** [PDFTron/webviewer-angular-sample#11]
This is not working

Run npm run build to build the development build of the project. Run npm run build-prod to build the production build of the project. The build artifacts will be stored in the dist/ directory.

To run the build, navigate to the dist/ directory, and run http-server. Navigate to the url: host:port/index.html to see the app (https://github.com/http-party/http-server/issues/525).

Logs:

```
sudo npm run build-prod

> webviewer-angular-sample@1.0.0 build-prod /var/www/webviewer-angular-sample
> ng build --prod

Browserslist: caniuse-lite is outdated. Please run next command `npm update`
 50% building 159/159 modules 0 activeKilled
```

dist/ folder is empty

**Comment by mparizeau-pdftron** [comment]
I just tried running this and I see this output:
```
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

chunk {0} runtime-es2015.3f3fc55b246d2a4b8254.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.9b611acffef2172caf79.js (main) 165 kB [initial] [rendered]
chunk {2} polyfills-es2015.aa0159c30890430c6766.js (polyfills) 36.2 kB [initial] [rendered]
chunk {3} styles.9acd367ced642784c7de.css (styles) 70 bytes [initial] [rendered]
Date: 2020-08-18T02:10:49.687Z - Hash: e833d95448e0dc47d845 - Time: 14930ms

chunk {0} runtime-es5.96f7c8f8b53ed2a89900.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es5.b146eaa33ecd887322ab.js (main) 191 kB [initial] [rendered]
chunk {2} polyfills-es5.2b136aa47637ca797fd7.js (polyfills) 119 kB [initial] [rendered]
Date: 2020-08-18T02:11:04.053Z - Hash: c6cd3e97668fa4e24f39 - Time: 14318ms
```

It looks like this creates a folder called `angular` inside the dist folder. So I navigated to dist/angular, ran http-server and I was able to see WebViewer load.

Does `npm run build-prod` fail with any errors for you? Or get stuck?

**Comment by ghost** [comment]
No Luck.

Does npm run build-prod fail with any errors for you? Or get stuck?
No it does not gives any error.

Node Version:
12.18.3

I am unable to see this chunks log
