### ISSUE TITLE
PowerPoint(.pptx) file notes are missing in web-view

### ISSUE THREAD

**Issue by jonycse** [PDFTron/webviewer-angular-sample#12]
I tried to display a .pptx file which also contains notes below each slide. Somehow [pdftron][1] remove/hide the notes. How can I display a slide with notes in it? Does [pdftron][1] have this feature?

[1]: https://www.pdftron.com/

**Comment by jonycse** [comment]
Here is the sample file I tried with.

[Travel_Presentation_PP.pptx](https://github.com/PDFTron/webviewer-angular-sample/files/5281378/Travel_Presentation_PP.pptx)

**Comment by mparizeau-pdftron** [comment]
Hi, you can read more about this here https://stackoverflow.com/a/64069324
