### ISSUE TITLE
PDFTRON watermark Removal

### ISSUE THREAD

**Issue by Aayush67** [PDFTron/webviewer-angular-sample#2]
Is it possible to remove PDFTRON watermarks that appear on each page?

**Comment by justinjung04** [comment]
If you [purchase license](https://www.pdftron.com/licensing) and pass it through a constructor option, the watermarks will be gone.

**Comment by Aayush67** [comment]
Any idea what is the charge for a plan?

**Comment by Aayush67** [comment]
Isn't it possible to make changes in the PDFTron library generating pdf to remove that watermark?

**Comment by justinjung04** [comment]
The watermark is the way to differentiate trial vs purchased, so it is not possible to remove them otherwise. You can fill in the form, and our sales representative will be in touch with you to discuss about your pricing options.

**Comment by Aayush67** [comment]
Here, since the library is not accessing any internet resource so isn't it possible to remove PDFTRON label by making changes to the files inside lib folder that is actually used to view/generate PDF.

**Comment by justinjung04** [comment]
In WebViewer, purchasing a license and passing it into the constructor is the only way to remove it. If you are looking for an open-source PDF solution, you can check out https://mozilla.github.io/pdf.js/

**Comment by Aayush67** [comment]
I am actually looking for open source pdf viewer with signature/annotation functionality in angular. This PDF.js is not providing this functionality. If you have any idea about the pdf viewer with signature functionality then plz suggest.

**Comment by justinjung04** [comment]
Sorry pdf.js is the only open source that I'm aware of. If you are still interested in using WebViewer, please fill out our [licensing form](https://www.pdftron.com/licensing/). I'll close this ticket.

**Comment by AhmedZamil** [comment]
to purchase is it possible only to purchase for using WebViewer
