### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by pemaju** [PDFTron/webviewer-angular-sample#24]
hi
Is there any possibilities for solve the issue raised while upload the document in pdf viewer.
Herewith i have attached the image for your reference.Kindly review it.

Thanks & Regards,
maju.
![Screenshot from 2022-10-01 12-56-47](https://user-images.githubusercontent.com/112880019/203477584-c22be40a-08bc-4cfc-982c-e3fff6577a57.png)
![Screenshot from 2022-09-26 18-04-32](https://user-images.githubusercontent.com/112880019/203477767-c5332ffb-a96e-437f-b676-8b37612ad0fa.png)
![Screenshot from 2022-11-21 15-58-28](https://user-images.githubusercontent.com/112880019/203478689-309e27b0-2c10-487f-b97d-63984773c7f9.png)

**Comment by mparizeau-pdftron** [comment]
From running this repo following the instructions here https://github.com/PDFTron/webviewer-angular-sample#initial-setup, we're not able to reproduce your issues.

Can you please submit a support ticket and submit a ticket here including more details about your issue https://www.pdftron.com/form/request/
