### ISSUE TITLE
Install stuck 

### ISSUE THREAD

**Issue by paramjit1992singh** [PDFTron/webviewer-angular-sample#9]
NPM install is always stuck here
![Capture](https://user-images.githubusercontent.com/17165533/79234239-9db83000-7e87-11ea-8a09-c1e8247ba73c.PNG)

**Comment by paramjit1992singh** [comment]
its been more than 1 hrs stuck here, can you check

**Comment by mparizeau-pdftron** [comment]
I just tried running `npm install` on Windows and it completed successfully for me. Maybe you could try cancelling and installing again.
